#spring.application.name=patient-service
# === Service Port & Name ===
# Give it a new, unique port
#server.port=8081

# === Eureka Discovery ===
# Tell this service where to find the Eureka server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# === MySQL Database Connection ===
# The location of your database (we will create 'claimconnect_db' next)
spring.datasource.url=jdbc:mysql://localhost:3306/claimconnect_db
# Your MySQL username (often 'root')
spring.datasource.username=root
# Your MySQL password (CHANGE THIS to your password)
spring.datasource.password=Srikar@2002

# === JPA / Hibernate Settings ===
# This tells Hibernate (part of JPA) to create/update tables automatically
spring.jpa.hibernate.ddl-auto=update
# This shows the SQL commands in your console, which is very helpful for debugging
spring.jpa.show-sql=true