spring.application.name=eureka-server
# Set the port for the server. 8761 is the standard default for Eureka.
server.port=8761

# Give our application a name
spring.application.name=eureka-server

# These two lines tell the Eureka Server NOT to register itself as a client.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false