# 1. Give this app a name (must match file name on GitHub)
spring.application.name=api-gateway

# 2. Tell this service where Eureka is
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# 3. Tell the gateway to load its config from the Config Server
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server

# 4. Retry settings (to wait for Config Server)
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=5000